<%@ Page Language="C#" Inherits="Freetime.Web.View.BaseViewPage" %>
<%--MasterPageFile="Site.Master" --%>
<asp:Content ID="indexTitle" ContentPlaceHolderID="TitleContent" runat="server">
    Freetime Development Platform
</asp:Content>

<asp:Content ID="indexContent" ContentPlaceHolderID="MainContent" runat="server">
    <h2>This is a themed image <%= IsEdit.ToString() %></h2>
    <%= Html.ThemedImage("hayley.jpg", new {@id = "imghayley"}) %>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque et tellus eget sapien vulputate porttitor non id est. Duis tincidunt ultrices justo, non sagittis justo blandit in. Suspendisse auctor dui non felis molestie quis suscipit felis interdum. Ut vitae consequat elit. Sed vitae massa sit amet dui elementum eleifend quis non enim. Suspendisse potenti. Vestibulum aliquet sodales diam eu mollis. Duis aliquam cursus enim consequat imperdiet. Quisque sed quam neque, sit amet elementum est. Duis sollicitudin varius libero, id commodo ligula vehicula sit amet. Etiam lorem massa, vulputate id placerat nec, laoreet a libero. Nulla consectetur lorem vitae sem hendrerit ac lobortis turpis feugiat. Aliquam orci erat, gravida vel suscipit quis, fermentum sed tortor. Sed imperdiet ipsum et est tempus a dapibus enim vestibulum. Duis scelerisque semper tortor eu molestie. Suspendisse mauris nulla, pretium at egestas ut, tincidunt quis neque. Nunc lacinia sem at lorem tristique egestas. Aenean augue metus, aliquet vel pharetra vel, fermentum eu sem.

Cras vehicula aliquet accumsan. Nunc ac ante velit, nec condimentum nunc. Pellentesque sit amet mi tellus, eget posuere nisi. Vivamus a tellus magna. Phasellus facilisis ornare gravida. Morbi id magna velit. Vestibulum rhoncus tincidunt nisi, in aliquet eros scelerisque ac. Curabitur pretium consequat nunc, sit amet venenatis ante accumsan nec. Aliquam imperdiet tincidunt tortor ac auctor. Curabitur cursus nisl ut tellus blandit auctor. Nullam volutpat turpis velit, sed lacinia diam. Nullam fringilla, risus condimentum condimentum sodales, purus orci tempus nisi, in euismod nisl lorem molestie turpis.

Donec tellus mauris, semper ac cursus nec, iaculis non turpis. Mauris posuere, elit vel posuere dictum, nunc felis interdum erat, ac eleifend odio dui quis magna. Proin dapibus accumsan dui fermentum faucibus. Ut vulputate orci eget leo ullamcorper pretium. Proin et nulla lectus, ut dapibus urna. Maecenas feugiat varius imperdiet. Proin luctus scelerisque est, non aliquet dui congue a. Sed venenatis, magna vitae porta volutpat, eros arcu interdum diam, vel pulvinar libero tortor consectetur velit. Aenean sodales, velit ut sagittis fringilla, risus orci tristique eros, sit amet aliquet enim turpis et mi. Nulla sed massa at velit vestibulum auctor at sit amet mauris. Mauris nunc arcu, vulputate sit amet pulvinar id, auctor at dolor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam a mauris elit, ac pharetra libero. Phasellus aliquam urna ut orci malesuada non aliquam nisi consequat. Donec varius dui sapien, a adipiscing massa. Integer eget mauris metus, nec consectetur dui. Sed nec mauris a libero feugiat bibendum at id dolor.

Aliquam erat volutpat. Mauris semper purus auctor magna mattis nec ullamcorper tortor blandit. Duis consectetur ante in sem semper varius eu ac justo. Vestibulum et dolor sit amet neque bibendum placerat eu semper mauris. Suspendisse potenti. Vivamus ullamcorper sodales purus, quis rhoncus erat dictum vitae. Suspendisse pharetra lacus vitae purus cursus tristique. Pellentesque velit leo, mattis eu auctor at, dapibus ut nibh. Quisque et dolor risus. Praesent libero neque, ultrices id convallis bibendum, fringilla eu libero.

Cras lorem diam, mollis a porttitor eget, porta ac mi. Vivamus sem est, facilisis vitae luctus eu, semper ut nisi. Curabitur viverra ornare lacus ac commodo. Nunc ut ipsum lectus, aliquet lobortis lectus. Quisque pellentesque, felis ut scelerisque gravida, nisi ante ornare erat, volutpat suscipit nunc quam ut nunc. Proin tempus iaculis hendrerit. Donec nisl turpis, malesuada iaculis pulvinar fermentum, blandit id dolor. Aenean semper, tortor quis condimentum ullamcorper, nibh dui venenatis quam, non tempor erat nisi ut erat. Curabitur et lorem turpis. Duis sit amet elit sed ipsum pulvinar facilisis in ac urna. Aliquam blandit felis vitae lectus tincidunt ultricies. Sed accumsan tortor a mauris eleifend mattis. Integer quis rhoncus turpis. Fusce commodo lacus euismod ante consequat at blandit leo ultricies. Integer quis est lorem, in vestibulum est. Vivamus volutpat nisi sit amet libero venenatis sodales. Duis auctor arcu et neque congue adipiscing. Nulla molestie dictum turpis, non bibendum velit euismod eget. Morbi rhoncus orci sed velit imperdiet laoreet condimentum eros tristique. In dui sapien, lacinia tempus lobortis eget, dictum non lorem. 
    </p>
</asp:Content>
